Setting:
  Repo:
  MaxThread: 4
Web:
  Port:
Database:
  Engine: mysql
  Path:
  Host:
  Username:
  Password:
  Port:
Log:
  App: app.log
  Database: db.log
  Level: 5
  MaxAge: 30
  MaxSize: 10
  MaxBackups: 3
  LocalTime: true
  Compress: true