Setting:
  Name: Mirror-repo
  Repo: ./repo
  Travel: 8
Web:
  Host: 127.0.0.1
  Port: 8080
Database:
  Engine: sqlite3
  Path: ./mirror.db
  Host: 127.0.0.1
  Username: tosone
  Password: 8541539655
  Port: 3306
Log:
  App: app.log
  ShowSQL: true
  Database: db.log
  Level: 5
  MaxAge: 30
  MaxSize: 10
  MaxBackups: 3
  LocalTime: true
  Compress: true
Mail:
  EMail: i@tosiney.com
  SMTP: smtp.mxhichina.com
  Port: 465
  Username: test@tosiney.com
  Password: testpassword